feature/SLNT-1_Initialize_extending_airbnb_config
supaapps/eslint-config-supaapps pull request #1
Opened 2023-10-25 11:39 UTC by MostafaFawzy7

2023-10-25 12:16 UTC, HassanElZarkawy requested changes

2023-10-25 12:16 UTC, HassanElZarkawy commented on index.js
> +module.exports = {
Can we put this file in a `src` directory? Keeping the conventions.

2023-10-25 12:16 UTC, HassanElZarkawy commented on index.js
> +    "import/no-extraneous-dependencies": "off",
Why did you disable this? I believe it prevents you from using dependencies that are not in `package.json`

2023-10-25 12:16 UTC, HassanElZarkawy commented on package.json
> +  "version": "1.0.1",
We typically use version `0.1.0` for the first release, and go on from there

2023-10-25 12:30 UTC, MostafaFawzy7 commented on index.js
> +module.exports = {
✅

2023-10-25 12:30 UTC, MostafaFawzy7 commented on index.js
> +    "import/no-extraneous-dependencies": "off",
✅

2023-10-25 12:31 UTC, MostafaFawzy7 commented on package.json
> +  "version": "1.0.1",
✅

2023-10-25 12:31 UTC, MostafaFawzy7 commented
> @MostafaFawzy7 There's no workflow? how are we going to integrate this?

✅

2023-10-25 12:31 UTC, MostafaFawzy7 commented on package.json
> +  "version": "1.0.1",
✅

2023-10-25 12:36 UTC, HassanElZarkawy commented on .github/workflows/build.yaml
> +    types: [ closed ]
```suggestion

```

2023-10-25 12:36 UTC, HassanElZarkawy commented on .github/workflows/build.yaml
> +    if: github.event.pull_request.merged == true
```suggestion

```

2023-10-25 13:36 UTC, MostafaFawzy7 commented on .github/workflows/build.yaml
> +          node-version: 14.x
✅

2023-10-25 13:38 UTC, MostafaFawzy7 commented
All comments have been resolved! ✅

2023-10-25 13:53 UTC, SirNarsh commented on .github/workflows/build.yaml
> +          node-version: latest
`latest` is not equal to `lts` , also let's switch to actions/setup-node@v3
<img width="844" alt="Screenshot 2023-10-25 at 15 52 36" src="https://github.com/supaapps/supa-eslint-config/assets/13707877/5a98d0e4-3703-4ce3-b9d0-de89b306e596">

2023-10-25 13:53 UTC, SirNarsh commented on .github/workflows/build.yaml
> +      - name: Use Node.js 14.x
fix name to avoid confusion

2023-10-25 13:54 UTC, SirNarsh commented on .github/workflows/build.yaml
> +    runs-on: ubuntu-18.04
let's switch to `lts` ubuntu 20 🙏

2023-10-25 14:07 UTC, MostafaFawzy7 commented on .github/workflows/build.yaml
> +      - run: npm publish
@SirNarsh here should we make it public?
```
- run: npm publish --access public
```

2023-10-25 14:15 UTC, MostafaFawzy7 commented on .github/workflows/build.yaml
> +      - name: Use Node.js 14.x
✅

2023-10-25 14:15 UTC, MostafaFawzy7 commented on .github/workflows/build.yaml
> +          node-version: latest
✅

2023-10-26 10:49 UTC, MostafaFawzy7 commented
@SirNarsh @HassanElZarkawy Revisit again as it should be ready now!

2023-10-26 11:11 UTC, moemen-zgtech reviewed
so far looking good to me, but i'm wondering if should we add `.prettierrc` file as well ?

2023-10-26 11:35 UTC, MostafaFawzy7 commented on .eslintrc
it's the same, `.eslintrc` is shortcut for `.eslintrc.json`

2023-10-26 11:36 UTC, MostafaFawzy7 commented
> so far looking good to me, but i'm wondering if should we add `.prettierrc` file as well ?

This would be added in the next ticket: `SLNT-2` which is for adding the complete config we intend to use and we already used it in `nao-referrals` app

2023-10-26 11:48 UTC, moemen-zgtech approved these changes

2023-10-27 08:43 UTC, SirNarsh commented
as discussed in daily `eslint-config-supaapps` to allow sharing

https://eslint.org/docs/latest/extend/shareable-configs

2023-10-27 12:30 UTC, MostafaFawzy7 commented
@SirNarsh Check the last 3 commits 🙏

2023-10-31 12:58 UTC, MostafaFawzy7 commented
@SirNarsh Build stuff reverted!

2023-11-01 08:56 UTC, HassanElZarkawy approved these changes

2023-11-01 09:25 UTC, moemen-zgtech approved these changes

2023-11-01 10:29 UTC, Abdallah-Abdelkhalek approved these changes

2023-11-01 12:24 UTC, merged